name: Beta

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ./github/workflows/**
    branches:
      - develop

env:
 S3_BUCKET: ${{ secrets.S3_BUCKET }}
 ZIP_FILE: ${{ secrets.ZIP_FILE }}

jobs:

   RoboHelp:
     name: "RoboHelp"
     runs-on: windows-2019
     env:
       LANGUAGE: ${{ vars.LANGUAGE }}
     steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Enable git long paths to bypass path limit on Windows
        run: git config --system core.longpaths true
      - name: Check out the GMS2_Documentation repo
        uses: actions/checkout@v3
        with:
          path: Manual  
          token: ${{ secrets.GH_TOKEN }}
      - name: Beta Builds
        if: github.event.pull_request.base.ref == 'develop' || github.event_name == 'workflow_dispatch'
        run: build_robohelp_gh.bat %GITHUB_WORKSPACE%\output
        shell: cmd
        working-directory: Manual       
      - name: Upload robohelp zip file
        uses: actions/upload-artifact@v3
        with:
           name: YoYoStudioRoboHelp
           path: output\RoboHelp\*.zip
           if-no-files-found: error
