name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 4 * * 1-5'   
  workflow_dispatch:  


jobs:
    sync_latest_from_upstream:
      runs-on: ubuntu-latest
      name: Sync latest commits from upstream repo  
      steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
      # - name: Sync upstream changes
      #   id: sync
      #   uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      #   with:
      #       target_sync_branch: develop
      #       # REQUIRED 'target_repo_token' exactly like this!
      #       target_repo_token: ${{ secrets.GH_TOKEN }}
      #       upstream_sync_branch: develop
      #       upstream_sync_repo: YoYoGames/GameMaker-Manual
      #       upstream_repo_access_token: ${{ secrets.GH_TOKEN }} 
      #       git_config_user: ksuchitra532 
      #       git_config_email: null
      #       git_config_pull_rebase: true      
      # - name: Sync upstream changes
      #   id: sync-lts
      #   uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      #   with:
      #         target_sync_branch: main-lts
      #         # REQUIRED 'target_repo_token' exactly like this!
      #         target_repo_token: ${{ secrets.GH_TOKEN }}
      #         upstream_sync_branch: main-lts
      #         upstream_sync_repo: YoYoGames/GameMaker-Manual
      #         upstream_repo_access_token: ${{ secrets.GH_TOKEN }}    
      - uses: AbdulmelikKalkan/sync-fork-upstream@v1.3
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          owner: YoYoGames
          repo: GameMaker-Manual
          branch: develop              

