name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 4 * * 1-5'   
  workflow_dispatch:  


jobs:
    sync_latest_from_upstream:
      runs-on: ubuntu-latest
      name: Sync latest commits from upstream repo  
      steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
      - name: repo-sync-develop
        uses: repo-sync/github-sync@v2
        with:
            source_repo: "https://${{ secrets.GH_TOKEN }}@github.com//YoYoGames/GameMaker-Manual.git"
            source_branch: "develop"
            destination_branch: "develop"
            github_token: ${{ secrets.GH_TOKEN }}
            sync_tags: "true"
      - name: repo-sync-lts-2022-r1
        uses: repo-sync/github-sync@v2
        with:
            source_repo: "https://${{ secrets.GH_TOKEN }}@github.com//YoYoGames/GameMaker-Manual.git"
            source_branch: "lts-2022-r*"
            destination_branch: "lts-2022-r*"
            github_token: ${{ secrets.GH_TOKEN }}
            sync_tags: "true"            

