name: Trigger-Localisation-Upstream-Sync-Builds

on:
  workflow_dispatch:
  

jobs:

  Trigger-Localisation-Upstream-Sync:
     runs-on: ubuntu-24.04
     strategy:
      matrix:
        language: [PT-BR, DE, ES, FR, IT, JA, KO, PL, RU, ZH] 
     steps:
      - name: Invoke Localisation Syncing
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sync.yml
          repo: YoYoGames/GameMaker-Manual-${{ matrix.language }}
          token: ${{ secrets.GH_TOKEN }} 
        continue-on-error: false 
       


                                                                       
